import hashlib

def fingerprint(content: str) -> str:
    return hashlib.sha256(content.encode()).hexdigest()

content = "This image was generated by an AI model1"
print("Fingerprint:", fingerprint(content))