def embed_watermark(text: str, marker="âŸ‚") -> str:
    words = text.split()
    watermarked = []

    for i, word in enumerate(words):
        watermarked.append(word)
        if i % 7 == 0:  # periodic pattern
            watermarked.append(marker)

    return " ".join(watermarked)

original = "This text was generated by an AI system for demonstration purposes."
wm = embed_watermark(original)

print("Original:", original)
print("Watermarked:", wm)